name: rug
description: "RUG — A multiplayer strategic card game revolving around the 3♣."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3

  # Routing
  go_router: ^17.3.0

  # Networking
  dio: ^5.9.2
  web_socket_channel: ^3.0.3
  connectivity_plus: ^7.2.0

  # Data & Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  uuid: ^4.5.3
  intl: ^0.20.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6

  # Firebase
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1

  # UI & Design
  google_fonts: ^8.1.0
  flutter_svg: ^2.3.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8

  # Animations
  flutter_animate: ^4.5.2
  lottie: ^3.4.0

  # Audio
  just_audio: ^0.10.6

  # Utilities
  logger: ^2.7.0
  permission_handler: ^12.0.3
  flutter_native_splash: ^2.4.8
  image_picker: ^1.2.3
  image_cropper: ^12.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  riverpod_generator: ^4.0.4

  # Linting
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.4

  # Testing
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/cards/
    - assets/logos/
    - assets/sounds/
    - assets/music/
    - assets/animations/
    - assets/lottie/
    - assets/json/

  # fonts:
  #   - family: Outfit
  #     fonts:
  #       - asset: assets/fonts/Outfit-Regular.ttf
  #       - asset: assets/fonts/Outfit-Bold.ttf
  #         weight: 700
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#050807"
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#050807"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#121016"
  adaptive_icon_foreground: assets/icons/app_icon.png
  adaptive_icon_foreground_inset: 0
  remove_alpha_ios: true
  background_color_ios: "#121016"
